apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/name: {{ include "guestbook.name" . }}
    helm.sh/chart: {{ include "guestbook.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ include "guestbook.fullname" . }}
spec:
  port:
    targetPort: {{ .Values.service.port }}-tcp
  to:
    kind: Service
    name: {{ include "guestbook.fullname" . }}
    weight: 100