---
apiVersion: v1
kind: Namespace
metadata:
  name: petclinic-app
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: petclinic-app-latest
  namespace: petclinic-app
spec:
  type: GitHub
  pathname: https://github.com/imsrv01/openshift-gitops.git
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: petclinic-app
  namespace: petclinic-app
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - petclinic-app
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: dev-clusters
  namespace: petclinic-app
spec:
  clusterConditions:
  - type: OK
  clusterSelector:
    matchLabels:
      purpose: development
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: petclinic-app
  namespace: petclinic-app
  labels:
    app: petclinic-app
  annotations:
      apps.open-cluster-management.io/github-path: apps/kustomize/petclinic/overlay/dev
      apps.open-cluster-management.io/github-branch: main
spec:
  channel: petclinic-app/petclinic-app-latest
  placement:
    placementRef:
      kind: PlacementRule
      name: dev-clusters
