apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-app-spring-petclinic
  namespace: openshift-gitops
spec:
  destination:
    namespace: dev-spring-petclinic
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/kustomize/petclinic/overlay/dev
    repoURL: https://github.com/imsrv01/openshift-gitops.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true